---
- name: install & configure RASsserver
  hosts: RAS
  become: yes

  tasks:
  - name: install epel-release
    ansible.builtin.yum:
      name: epel-release
      state: present

  - name: install soft
    ansible.builtin.yum:
      name:
      - openvpn
      - easy-rsa
      state: present

  - name: disabled selinux
    ansible.posix.selinux:
      state: disabled

  - name: init pki
    ansible.builtin.shell:
      cmd: /usr/share/easy-rsa/3.0.8/easyrsa init-pki
      chdir: /etc/openvpn/
    register: result

  - name: register result
    ansible.builtin.debug:
      var=result

  - name: create sertificate & key for server
    ansible.builtin.shell: 
      cmd: "echo 'rasvpn' | /usr/share/easy-rsa/3.0.8/easyrsa build-ca nopass"
      chdir: /etc/openvpn/

  - name: create sertificate & key for server
    ansible.builtin.shell:
      cmd: "echo 'rasvpn' | /usr/share/easy-rsa/3.0.8/easyrsa gen-req server nopass"
      chdir: /etc/openvpn/

  - name: create sertificate & key for server
    ansible.builtin.shell:
      cmd: "echo 'yes' | /usr/share/easy-rsa/3.0.8/easyrsa sign-req server server"
      chdir: /etc/openvpn/

  - name: create sertificate & key for server
    ansible.builtin.shell:
      cmd: "/usr/share/easy-rsa/3.0.8/easyrsa gen-dh"
      chdir: /etc/openvpn/

  - name: create sertificate & key for server
    ansible.builtin.shell:
      cmd: "openvpn --genkey --secret ca.key"
      chdir: /etc/openvpn/

  - name: create sertificate & key for server
    ansible.builtin.shell:
      cmd: "echo 'client' | /usr/share/easy-rsa/3/easyrsa gen-req client nopass"
      chdir: /etc/openvpn/

  - name: create sertificate & key for server
    ansible.builtin.shell:
      cmd: "echo 'yes' | /usr/share/easy-rsa/3/easyrsa sign-req client client"
      chdir: /etc/openvpn/

  - name: copy conffile for server
    ansible.builtin.copy:
      src: server.conf
      dest: /etc/openvpn/server.conf
      remote_src: no

  - name: create rule for iroute
    ansible.builtin.shell:
      cmd: "echo 'iroute 10.10.10.0 255.255.255.0' > /etc/openvpn/client/client"

  - name: copy unit file for openvpn service
    ansible.builtin.copy:
      src: openvpn@.service
      dest: /etc/systemd/system/openvpn@.service
      remote_src: no

  - name: start & enable openvpn.service
    ansible.builtin.service:
      name: openvpn@server
      state: started
      enabled: yes

  - name: copy sertificate from server
    ansible.builtin.copy:
      src: /etc/openvpn/pki/ca.crt
      dest: /vagrant
      remote_src: yes

  - name: copy sertificate from server
    ansible.builtin.copy:
      src: /etc/openvpn/pki/issued/client.crt
      dest: /vagrant
      remote_src: yes

  - name: copy sertificate from server
    ansible.builtin.copy:
      src: /etc/openvpn/pki/private/client.key
      dest: /vagrant
      remote_src: yes
...
