---
- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install soft
  yum:
    name:
    - openvpn
    - iperf3
    state: present
    update_cache: true

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: create conffile for openvpn_client
  copy:
    src: server.conf
    dest: /etc/openvpn/server.conf

- name: create service_unit openvpn
  copy:
    src: openvpn@.service
    dest: /etc/systemd/system/openvpn@.service

- name: copy static.key
  copy:
    src: /vagrant/static.key
    dest: /etc/openvpn
    remote_src: yes

- name: enable & start openvpn.service
  systemd:
    name: openvpn@server.service
    state: started
    enabled: true
...
