# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
 :server => {
        :box_name => "centos/7",
        :vm_name => "server",
        :net => [
                   {ip: '192.168.56.10', adapter: 2, netmask: "255.255.255.0"}
               ]
  },

 :client => {
        :box_name => "centos/7",
        :vm_name => "client",
        :net => [
                   {ip: '192.168.56.20', adapter: 2, netmask: "255.255.255.0"}
               ]
  },

}

Vagrant.configure("2") do |config|

   config.vm.synced_folder '.', '/vagrant', disabled: true
   config.vm.synced_folder '.', '/vagrant', create: true, type: 'sshfs', disabled: false

  MACHINES.each do |boxname, boxconfig|

       config.vm.define boxname do |box|
       box.vm.box = boxconfig[:box_name]
       box.vm.host_name = boxconfig[:vm_name]
       
              if boxconfig[:vm_name] == "client"
                 box.vm.provision "ansible" do |ansible|
                  ansible.playbook = "ansible/provision.yml"
                  ansible.host_key_checking = "false"
                  ansible.limit = "all"
               end
                         
          end
               
       boxconfig[:net].each do |ipconf|
       box.vm.network "private_network", ipconf
       
      end
               
          box.vm.provision "shell", inline: <<-SHELL
             mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
             SHELL
     end      
   end
end
